Update README.md

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,17 +9,16 @@ jobs:
       # specify the version you desire here
       - image: cimg/openjdk:20.0.1
 
-      - image: cimg/mysql:8.0
-        environment:
-          DB_ROOT_USER: root
-          DB_URL: jdbc:mysql://localhost:3306/restdb
-          DB_DRIVER: com.mysql.cj.jdbc.Driver
-          DB_PASS: root
+        # Specify service dependencies here if necessary
+        # CircleCI maintains a library of pre-built images
+        # documented at https://circleci.com/docs/2.0/circleci-images/
 
-      # Specify service dependencies here if necessary
-      # CircleCI maintains a library of pre-built images
-      # documented at https://circleci.com/docs/2.0/circleci-images/
-      # - image: circleci/postgres:9.4
+    #      - image: cimg/mysql:8.0
+    #        environment:
+    #          DB_ROOT_USER: root
+    #          DB_URL: jdbc:mysql://localhost:3306/restdb
+    #          DB_DRIVER: com.mysql.cj.jdbc.Driver
+    #          DB_PASS: root
 
     working_directory: ~/repo
 
@@ -39,22 +38,22 @@ jobs:
 
       - run: mvn dependency:go-offline
 
-      - run:
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 30`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+      #      - run:
+      #          name: Waiting for MySQL to be ready
+      #          command: |
+      #            for i in `seq 1 30`;
+      #            do
+      #              nc -z 127.0.0.1 3306 && echo Success && exit 0
+      #              echo -n .
+      #              sleep 1
+      #            done
+      #            echo Failed waiting for MySQL && exit 1
 
-      #install mysql client
-      - run: sudo apt update
-      - run: sudo apt-get install mysql-client
-      # create databases
-      - run: mysql -h 127.0.0.1 -u root -e "create database restdb"
+      #      #install mysql client
+      #      - run: sudo apt update
+      #      - run: sudo apt-get install mysql-client
+      #      # create database
+      #      - run: mysql -h 127.0.0.1 -u root -e "create database restdb"
 
       - save_cache:
           paths:
